/*
 * Home Action Types
 *
 */

export const LOAD_PATIENT_INFO = 'Home/LOAD_PATIENT_INFO';
export const LOAD_PATIENT_INFO_SUCCESS = 'Home/LOAD_PATIENT_INFO_SUCCESS';
export const LOAD_PATIENT_INFO_ERROR = 'Home/LOAD_PATIENT_INFO_ERROR';
